<?php

namespace am\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KarfarmaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KarfarmaRepository extends EntityRepository
{
}
