<?php

namespace am\KaryabBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertiseRepository extends EntityRepository
{
    public function findOnePublished($id)
    {
        return $this->findOneBy(array('id'=>$id));
    }

}
