<?php

namespace am\KaryabBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * jobRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jobRequestRepository extends EntityRepository
{
}
