am\KaryabBundle\Entity\Advertise:
    type: entity
    table: se_advertises
    repositoryClass: am\KaryabBundle\Repository\AdvertiseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255

        description:
            type: text
            nullable: true

        grade:
            type: integer
            nullable: true

        coOperation:
            type: json_array
            nullable: true

        gender:
            type: smallint
            nullable: true

        otherSkills:
            type: text
            nullable: true

        soldiery:
            type: smallint
            nullable: true

        createdAt:
            type: datetime
            nullable: true

        isPublished:
            type: boolean
            options:
                default: true

        isDeleted:
            type: boolean
            options:
                default: false

        brochure:
            type: string
            length: 255
            nullable: true

        expireDate:
            type: date

    manyToMany:
        skillTags:
          targetEntity: am\KaryabBundle\Entity\SkillTag
          inversedBy: advertises
          joinTable:
            name: se_advertise_tags
            joinColumns:
              advertise_id:
                referencedColumnName: id
            inverseJoinColumns:
              tag_id:
                referencedColumnName: id
    manyToOne:
        user:
          targetEntity: am\UserBundle\Entity\User
          inversedBy: advertises
          joinColumn:
            name: user_id
            referencedColumnName: id
    oneToMany:
        jobRequests:
          targetEntity: am\KaryabBundle\Entity\jobRequest
          mappedBy: advertise
    lifecycleCallbacks: {  }
