am\KaryabBundle\Entity\jobRequest:
    type: entity
    table: se_job_requests
    repositoryClass: am\KaryabBundle\Repository\jobRequestRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        minimumSalary:
            type: integer
    manyToOne:
        user:
          targetEntity: am\UserBundle\Entity\User
          inversedBy: jobRequests
          joinColumn:
            name: user_id
            referencedColumnName: id
        advertise:
          targetEntity: am\KaryabBundle\Entity\Advertise
          inversedBy: jobRequests
          joinColumn:
            name: advertise_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
