swdt\KaryabBundle\Entity\Contacts:
    type: entity
    table: se_contacts
    repositoryClass: swdt\KaryabBundle\Repository\ContactsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
        subject:
            type: string
            length: 255
            nullable: true
        message:
            type: text
        createdAt:
            type: datetime
        iPAddress:
            type: string
            length: 255
            column: IPAddress
    lifecycleCallbacks: {  }