<?php

namespace swdt\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KarjooRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KarjooRepository extends EntityRepository
{
}
