swdt_karyab_homepage:
    path:     /
    defaults: { _controller: swdtKaryabBundle:Default:index }

#swdt_karyab_about:
#    path:     /about
#    defaults: { _controller: swdtKaryabBundle:pages:about }

swdt_karyab_contact_us:
    path:     /contactUs
    defaults: { _controller: swdtKaryabBundle:pages:contactUs }

swdt_karyab_dashboard:
    path:     /dashboard
    defaults: { _controller: swdtUserBundle:pages:index }

swdt_karyab_published_advertises_for_karjoo:
    path:     /published_advertises
    defaults: { _controller: swdtKaryabBundle:advertises:published }

swdt_karyab_relevant_advertises_for_karjoo:
    path:     /panel/karjoo/relevant_advertises
    defaults: { _controller: swdtKaryabBundle:advertises:relevant }

swdt_karyab_advertise_new:
    path:     /panel/karfarma/advertise/new
    defaults: { _controller: swdtKaryabBundle:advertises:new }

swdt_karyab_advertise_edit:
    path:     /panel/karfarma/advertise/edit/{id}
    defaults: { _controller: swdtKaryabBundle:advertises:edit }

swdt_karyab_advertise_delete:
    path:     /panel/karfarma/advertise/delete/{id}
    defaults: { _controller: swdtKaryabBundle:advertises:delete }

swdt_karyab_advertise_disable:
    path:     /panel/karfarma/advertise/disable/{id}
    defaults: { _controller: swdtKaryabBundle:advertises:disable }

swdt_karyab_advertise_enable:
    path:     /panel/karfarma/advertise/enable/{id}
    defaults: { _controller: swdtKaryabBundle:advertises:enable }

karyab_karfarma_advertise_index:
    path:     /panel/karfarma/advertise
    defaults: { _controller: swdtKaryabBundle:advertises:listKarfarama }

mz_ajax_advertise_request:
    path:     /panel/karjoo/sendRequest
    defaults: { _controller: swdtKaryabBundle:ajax:sendRequest }
    methods: [POST]

mz_ajax_search_tags:
    path:     /ajax/tags
    defaults: { _controller: swdtKaryabBundle:ajax:searchTags }
    methods: [POST]