<?php

/*
 * This file is part of the FOSUserBundle package.
 *
 * (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace swdt\UserBundle\Form;

use FOS\UserBundle\Util\LegacyFormHelper;
use Gregwar\CaptchaBundle\Type\CaptchaType;
use swdt\KaryabBundle\Form\userSkillsFormType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class Registration_karjooFormType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('fName','text',array(
                'label' =>'نام',
                'max_length' => 50,
                'attr' => array(
                    'placeholder' => 'نام خود را وارد کنید',
                )
            ))
            ->add('lName','text',array(
                'label' =>'نام خانوادگی',
                'max_length' => 50,
                'attr' => array(
                    'placeholder' => 'نام خانوادگی خود را وارد کنید',
                )
            ))
            ->add('gender','choice',array(
                'label' =>'جنسیت',
                'placeholder' => 'جنسیت خود را انتخاب کنید',
                'choices' => array(1=> 'آقا' , 2 => 'خانم' ),
                'multiple' => false,
            ))
            ->add('birth_year','text',array(
                'label' => 'سال تولد',
                'max_length'=>4,
                'required' => false,
                'attr' => array(
                    'placeholder' => 'سال تولد خود را وارد کنید(هر ۴ رقم)',
                    'min' => 1300,
                    'max' => date('Y') - 621,
                )
            ))
            ->add('mobile','text',array(
                'label' => 'شماره تماس',
                'max_length' => 12,
                'attr' => array(
                    'placeholder' => 'شماره تماس خود را وارد کنید',
                )

            ))
            ->add('skills','Symfony\Component\Form\Extension\Core\Type\CollectionType',array(
                'label' => ' ',
                'entry_type' => new userSkillsFormType(),
                'allow_add' => true,
                'allow_delete' => true,
            ))
        ;
    }

    public function getParent()
    {
        return 'FOS\UserBundle\Form\Type\RegistrationFormType';

        // Or for Symfony < 2.8
        // return 'fos_user_registration';
    }

    public function getBlockPrefix()
    {
        return 'swdt_user_registration';
    }

    // For Symfony 2.x
    public function getName()
    {
        return $this->getBlockPrefix();
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver); // TODO: Change the autogenerated stub

        $resolver->setDefaults(array('cascade_validation' => true,));
    }
}
