am\UserBundle\Entity\Karjoo:
    type: entity
    table: se_karjoo_extra
    repositoryClass: am\UserBundle\Repository\KarjooRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        about:
            type: text
            nullable: true
        avatar:
            type: string
            length: 255
            nullable: true
        telephone:
            type: string
            length: '12'
            nullable: true
        resume:
            type: text
            nullable: true

        website:
            type: string
            nullable: true
        coOperation:
            type: json_array
            nullable: true
    oneToOne:
        user:
          targetEntity: am\UserBundle\Entity\User
          inversedBy: karjoo
          joinColumn:
            name: user_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
