swdt\UserBundle\Entity\User:
    type: entity
    table: swdt_users
    repositoryClass: swdt\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fName:
            type: string
            length: '50'

        lName:
            type: string
            length: '50'

        gender:
            type: smallint
            nullable: true

        birthYear:
            type: integer
            nullable: true

        mobile:
            type: string
            length: '12'
            unique: false

    oneToMany:
        skills:
          targetEntity: swdt\KaryabBundle\Entity\UserSkill
          mappedBy: user
          cascade: [persist]
        advertises:
          targetEntity: swdt\KaryabBundle\Entity\Advertise
          mappedBy: user
        jobRequests:
          targetEntity: swdt\KaryabBundle\Entity\jobRequest
          mappedBy: user
    oneToOne:
        karjoo:
          targetEntity: swdt\UserBundle\Entity\Karjoo
          mappedBy: user
          cascade: [persist]
        karfarma:
          targetEntity: swdt\UserBundle\Entity\Karfarma
          mappedBy: user
          cascade: [persist]

    lifecycleCallbacks: {}


