<?php

/*
 * This file is part of the FOSUserBundle package.
 *
 * (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace am\UserBundle\Form;

use EWZ\Bundle\RecaptchaBundle\Form\Type\EWZRecaptchaType;
use Gregwar\CaptchaBundle\Type\CaptchaType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use EWZ\Bundle\RecaptchaBundle\Validator\Constraints\IsTrue as RecaptchaTrue;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class Registration_karfarmaFormType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('fName','text',array(
                'label' =>'نام',
                'max_length' => 50,
                'attr' => array(
                    'placeholder' => '',
                )
            ))
            ->add('lName','text',array(
                'label' =>'نام خانوادگی',
                'max_length' => 50,
                'attr' => array(
                    'placeholder' => '',
                )
            ))
            /*->add('gender','choice',array(
                'label' =>'جنسیت',
                'required' => false,
                'placeholder' => '',
                'choices' => array(1=> 'مرد' , 2 => 'زن' ),
                'multiple' => false,
            ))
            ->add('birth_year','text',array(
                'label' => 'سال تولد',
                'required' => false,
                'attr' => array(
                    'placeholder' => '',
                    'min' => 1300,
                    'max' => date('Y') - 621,
                )

            ))*/
            ->add('mobile','text',array(
                'label' => 'شماره موبایل',
                'max_length' => 12,
                'attr' => array(
                    'placeholder' => '',
                )
            ))
            ->add('karfarma',new Registration_karfarmaExtraFormType())
        ;

    }


    public function getParent()
    {
        return 'FOS\UserBundle\Form\Type\RegistrationFormType';

        // Or for Symfony < 2.8
        // return 'fos_user_registration';
    }

    public function getBlockPrefix()
    {
        return 'am_user_registration';
    }

    // For Symfony 2.x
    public function getName()
    {
        return $this->getBlockPrefix();
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver); // TODO: Change the autogenerated stub

//        $resolver->setDefaults(array('cascade_validation' => true,));
    }
}
